# Generated by Django 5.2.13 on 2026-04-07 15:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Nachname')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Mitarbeiter')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Registriert')),
                ('microsoft_oid', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Microsoft OID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Benutzer',
                'verbose_name_plural': 'Benutzer',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='AppRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('spielbetrieb', 'Spielbetrieb'), ('vereinsheimbuchung', 'Vereinsheimbuchung'), ('tenniscourts', 'Tenniscourts'), ('vereinsheim', 'Vereinsheim')], max_length=50, verbose_name='Anwendung')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('koordinator', 'Koordinator'), ('benutzer', 'Benutzer / Trainer'), ('verwaltung', 'Verwaltung'), ('viewer', 'Nur lesen')], max_length=50, verbose_name='Rolle')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Vergeben am')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_roles', to=settings.AUTH_USER_MODEL, verbose_name='Vergeben von')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Rollenzuweisung',
                'verbose_name_plural': 'Rollenzuweisungen',
                'ordering': ['app', 'user__last_name'],
                'unique_together': {('user', 'app')},
            },
        ),
    ]
