# Generated by Django 5.2.13 on 2026-04-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approleassignment',
            name='team',
            field=models.CharField(blank=True, help_text='Nur für Spielbetrieb-Trainer relevant. Exakt so schreiben wie in der Saisonplanung.', max_length=100, verbose_name='Mannschaft'),
        ),
    ]
