# Generated by Django 5.2.13 on 2026-04-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_approleassignment_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approleassignment',
            name='app',
            field=models.CharField(choices=[('spielbetrieb', 'Spielbetrieb'), ('vereinsheimbuchung', 'Vereinsheimbuchung'), ('tenniscourts', 'Tenniscourts'), ('vereinsheim', 'Vereinsheim'), ('kursanmeldung', 'Kursanmeldung')], max_length=50, verbose_name='Anwendung'),
        ),
        migrations.AlterField(
            model_name='approleassignment',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('koordinator', 'Koordinator'), ('benutzer', 'Benutzer / Trainer'), ('verwaltung', 'Verwaltung'), ('viewer', 'Nur lesen'), ('kassierer', 'Kassierer'), ('kursleitung', 'Kursleitung')], max_length=50, verbose_name='Rolle'),
        ),
    ]
