# Generated by Django 5.2.13 on 2026-04-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_kursanmeldung_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Wenn gesetzt, wird der Benutzer nach dem Login sofort zur Passwort-Änderung weitergeleitet.', verbose_name='Passwort beim nächsten Login ändern'),
        ),
        migrations.AlterField(
            model_name='approleassignment',
            name='app',
            field=models.CharField(choices=[('spielbetrieb', 'Spielbetrieb'), ('vereinsheimbuchung', 'Vereinsheimbuchung'), ('tenniscourts', 'Tenniscourts'), ('vereinsheim', 'Vereinsheim'), ('kursanmeldung', 'Kursanmeldung'), ('schluesselverwaltung', 'Schlüsselverwaltung')], max_length=50, verbose_name='Anwendung'),
        ),
    ]
