# Generated by Django 5.2.13 on 2026-05-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_must_change_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approleassignment',
            name='app',
            field=models.CharField(choices=[('spielbetrieb', 'Spielbetrieb'), ('vereinsheimbuchung', 'Vereinsheimbuchung'), ('tenniscourts', 'Tenniscourts'), ('vereinsheim', 'Vereinsheim'), ('kursanmeldung', 'Kursanmeldung'), ('schluesselverwaltung', 'Schlüsselverwaltung'), ('kalender', 'Vereinskalender')], max_length=50, verbose_name='Anwendung'),
        ),
    ]
